backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Banner"
      name: "banner"
      file: "src/content/content.md"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false}
        - { label: "Date", name: "date", widget: "datetime", required: false}
    - label: "Tags"
      name: "tags"
      widget: "list"
      default: ["news"]