backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Banner"
      name: "banner"
      file: "src/content/content.md"
      fields:
        - { label: "Title_Deutsch", name: "title_de", widget: "string", required: false}
        - { label: "Title_English", name: "title_en", widget: "string", required: false}
        - { label: "Date", name: "date", widget: "datetime", required: false}
        - { label: "isStartDate", name: "is_start_date", widget: "boolean", required: true }
        - { label: "Show_Date", name: "show_date", widget: "boolean", required: true }
        - { label: "Show_Banner", name: "show_banner", widget: "boolean", required: true }
    - label: "Testimonials"
      name: "testimonials"
      file: "src/content/testimonials.md"
      fields:
        - label: "Testimonials"
          name: "testimonials"
          widget: "list"
          fields:
            - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
            - {label: Author, name: author, widget: string }