backend:
  name: git-gateway
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Content"
      name: "content"
      file: "src/content/content.md"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false}
        - { label: "Date", name: "date", widget: "datetime", required: false}
