backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Banner"
      name: "banner"
      file: "src/content/content.md"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false}
        - { label: "Date", name: "date", widget: "datetime", required: false}
    - label: "Testimonials"
      name: "testimonials"
      file: "src/content/testimonials.md"
      widget: "list"
      allow_add: true
      summary: '{{fields.quote}} - {{fields.name}}'
      fields:
        - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
        - {label: Name, name: name, widget: string, default: ""}
      default:
      - { quote: "test quote default", name: "name" }
      - { quote: "test quote 2", name: "name2" }